default_language_version:
  python: python3.13

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-toml
    -   id: check-yaml
        args: ['--unsafe']
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: mixed-line-ending

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
    -   id: ruff
        args: ['--fix', '--line-length=120', '--exit-non-zero-on-fix', '--show-fixes']

-   repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
    -   id: black
        args: ['--line-length=120']

-   repo: https://github.com/pycqa/pylint
    rev: v4.0.5
    hooks:
    -   id: pylint
        args:
        -   '--max-positional-arguments=8'
        -   '--max-line-length=120'
        -   '-d duplicate-code'
        -   '--disable=import-error'
        -   '--disable=W0511, C0103, C0411, line-too-long, I1101'  # Disable line-too-long since it's handled by Black/Ruff

-   repo: https://github.com/asottile/blacken-docs
    rev: 1.20.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==24.2.0]

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=120", "--max-complexity=10", "--extend-ignore=D203,D212,E203,E251,E266,E302,E305,E401,E402,E501,F401,F403,W503",
          "--exclude=.git,__pycache__"]

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        additional_dependencies:
        -   tomli


-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pycqa/isort
    rev: 8.0.0
    hooks:
    -   id: isort
        args: ['--profile', "black"]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: ['--py38-plus']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        args: [--disallow-untyped-defs, --disallow-incomplete-defs,
              --disallow-untyped-calls, --follow-imports, 'normal',
              --ignore-missing-imports]
        additional_dependencies: [types-python-dateutil, types-requests,
              types-toml, types-pytz, types-PyYAML]
